name: test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install, Test, and Build 🔧
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install, Test, and Build 🔧
        run: |
          npm install
          npm run test
          npm run build
